server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/felipec03/Evaluacion2-tingeso-karting-rm  # Replace with your Git repo or use file:///path/to/local/repo
          default-label: main  # Or master, depending on your branch name
          search-paths: '*'  # Search all subdirectories