server:
  port: 8085

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-tarifasconfig
          uri: lb://ms-tarifasconfig
          predicates:
            - Path=/api/tarifas/**, /api/configuracion/**
        # Add routes for your other microservices here

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost