server:
  port: 8085

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: ms-tarifasconfig
          uri: lb://ms-tarifasconfig
          predicates:
            - Path=/ms-tarifasconfig/**
          filters:
            - StripPrefix=1
        - id: ms-descuentoporpersona
          uri: lb://ms-descuentoporpersona
          predicates:
            - Path=/ms-descuentoporpersona/**
          filters:
            - StripPrefix=1
        - id: ms-descuentosclientefrecuente
          uri: lb://ms-descuentosclientefrecuente
          predicates:
            - Path=/ms-descuentosclientefrecuente/**
          filters:
            - StripPrefix=1
        - id: ms-tarifadiaespecial
          uri: lb://ms-tarifadiaespecial
          predicates:
            - Path=/ms-tarifadiaespecial/**
          filters:
            - StripPrefix=1
        - id: ms-registroreserva-comprobantepago
          uri: lb://ms-registroreserva-comprobantepago
          predicates:
            - Path=/api/registroreserva-comprobantepago/**
          filters:
            - StripPrefix=1
        - id: ms-racksemanal
          uri: lb://ms-racksemanal
          predicates:
            - Path=/ms-racksemanal/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true