server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        gateway:
          discovery:
            locator:
              enabled: true
          routes:
            - id: ms-tarifasconfig
              uri: lb://ms-tarifasconfig
              predicates:
                - Path=/api/tarifas/**, /api/configuracion/**