server:
  port: 0 # Puerto dinámico, Eureka se encargará

spring:
  application:
    name: ms-racksemanal
  cloud:
    config:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/ # URL del servicio Eureka en Kubernetes