apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  labels:
    app: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: felipec03/gateway-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "gateway-server-service"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  labels:
    app: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: NodePort # Changed from LoadBalancer for Minikube