apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  labels:
    app: gateway-server
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: clustertingesoregistry.azurecr.io/gateway-server:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_CONFIG_SERVER_URI
              value: "http://config-server-service:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  labels:
    app: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer