apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-registroreserva-comprobantepago-deployment
  labels:
    app: ms-registroreserva-comprobantepago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-registroreserva-comprobantepago
  template:
    metadata:
      labels:
        app: ms-registroreserva-comprobantepago
    spec:
      containers:
        - name: ms-registroreserva-comprobantepago
          image: felipec03/ms-registroreserva-comprobantepago:latest 
          imagePullPolicy: Always 

          ports:
            - containerPort: 8080 
          env:
            - name: SPRING_APPLICATION_NAME
              value: "ms-registroreserva-comprobantepago" 
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server-service:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_URL_MS5
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_USERNAME 
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"                           
---
apiVersion: v1
kind: Service
metadata:
  name: ms-registroreserva-comprobantepago-service
  labels:
    app: ms-registroreserva-comprobantepago
spec:
  selector:
    app: ms-registroreserva-comprobantepago
  ports:
    - protocol: TCP
      port: 8080      
      targetPort: 8080