apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tarifasconfig-deployment
  labels:
    app: ms-tarifasconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-tarifasconfig
  template:
    metadata:
      labels:
        app: ms-tarifasconfig
    spec:
      containers:
      - name: ms-tarifasconfig
        image: felipec03/ms-tarifasconfig:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091
        env:
        - name: SPRING_CONFIG_IMPORT
          value: "configserver:http://config-server-service:8888"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-server-service:8761/eureka/"
        - name: DB_HOST_TARIFAS
          value: "postgres"
        - name: DB_NAME_TARIFAS
          value: "tarifas_db"
        - name: DB_USERNAME_TARIFAS
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: username
        - name: DB_PASSWORD_TARIFAS
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: ms-tarifasconfig-service
  labels:
    app: ms-tarifasconfig
spec:
  selector:
    app: ms-tarifasconfig
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP