apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tarifasconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-tarifasconfig
  template:
    metadata:
      labels:
        app: ms-tarifasconfig
    spec:
      containers:
        - name: ms-tarifasconfig
          image: ms-tarifasconfig:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "ms-tarifasconfig"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server-service:8761/eureka/"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "true"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            # Variables para la base de datos, si las necesitas:
            - name: SPRING_DATASOURCE_URL_MS1
              value: "jdbc:postgresql://<host>:<port>/<db>"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-tarifasconfig
  labels:
    app: ms-tarifasconfig
spec:
  selector:
    app: ms-tarifasconfig
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort