apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:13
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
            - name: init-db-scripts 
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes: 
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: init-db-scripts
          configMap:
            name: postgres-init-dbs-scripts 
            defaultMode: 0755 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-dbs-scripts
data:
  01-create-databases.sql: | 
    CREATE DATABASE ms1;
    CREATE DATABASE ms2;
    CREATE DATABASE ms3;
    CREATE DATABASE ms4;
    CREATE DATABASE ms5;
    CREATE DATABASE ms6;