// filepath: d:\Universidad\Ingeniería Civil Informática\Séptimo Semestre\Técnicas de Ingeniería de Software\Evaluaciones\Evaluacion2-tingeso-karting-rm\eureka-server\src\main\resources\application.yml
server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/